#!/bin/bash

source_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd "$source_dir"

echo "Installing node modules"
npm install -i

# Install services
echo "Installing services"
services="chat"
for service in $services; do
  skel="${service}.service.skel"
  temp="${service}.service"
  sudo sed "s#{{directory}}#${source_dir}#g" < $skel > $temp
  sudo mv $temp /etc/systemd/system/
done
sudo systemctl daemon-reload

echo "Enabling services"
enabled_services="chat"
for service in $enabled_services; do
  sudo systemctl enable "$service"
done

echo "Install Complete!"
